<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for mojo-errors</title>
  </head>
  <body>
    <h1>Links for mojo-errors</h1>
<a href="https://files.pythonhosted.org/packages/67/4a/613643d5d345dc4b561813657f18e8c46e0833a87171e823fa75eced48a4/mojo_errors-0.0.1-py3-none-any.whl#sha256=2fce119addbba21b2f59d0dff47c1267a1fc9dbc5e0788f89966a00cc35946e8" data-requires-python="&gt;=3.8,&lt;4.0" data-dist-info-metadata="sha256=17c2560eb9ca371d74d11c20ab2bffbb056ef2eda0e305507de62093603e5d78" data-core-metadata="sha256=17c2560eb9ca371d74d11c20ab2bffbb056ef2eda0e305507de62093603e5d78">mojo_errors-0.0.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/07/14/9253d4a9d41f28dc91b0a0830f05d251111c9e7f110f93008041d2b9abd9/mojo_errors-0.0.1.tar.gz#sha256=9f2bf0c11ef7f334e136f5259101e56f4ba68fb7ee6023e9b0bb253019a1bdf5" data-requires-python="&gt;=3.8,&lt;4.0" >mojo_errors-0.0.1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/a5/4a/fa0697043ff415b4773a380e36c86acaa2785f77ae62c47da9ea5c4633d9/mojo_errors-0.0.2-py3-none-any.whl#sha256=2800296d2c06b2adfd38c7e169cf717e7a1d71629b3329dd8f84590469c8bbb9" data-requires-python="&gt;=3.8,&lt;4.0" data-dist-info-metadata="sha256=9e0708d4cd715fa20bea44f1dbf3d2853edace3e53388b44a97665e31406e51d" data-core-metadata="sha256=9e0708d4cd715fa20bea44f1dbf3d2853edace3e53388b44a97665e31406e51d">mojo_errors-0.0.2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/7a/e4/4829091df38b70dd1d2cb317f4aa0dfc18f5ad6ff46c44cbe521903616b1/mojo_errors-0.0.2.tar.gz#sha256=8b966e8f08b16f418a763e1bc1fd30c0c2c71319488e81e8c77452e9fc576426" data-requires-python="&gt;=3.8,&lt;4.0" >mojo_errors-0.0.2.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/54/49/08dfb364fe7b053aaffb2de18c10ed5f2e6d0af1d6eb655a2b2527e108d9/mojo_errors-0.0.3-py3-none-any.whl#sha256=08605759cd84171da07e5945b212fc73129eeefa972e7e55b282e2dbb140050b" data-requires-python="&gt;=3.8,&lt;4.0" data-dist-info-metadata="sha256=9037247dd53cc5a3cdcfe1f8f568f6c0c5146fe294db2cc5668d0c7ea86c3b1c" data-core-metadata="sha256=9037247dd53cc5a3cdcfe1f8f568f6c0c5146fe294db2cc5668d0c7ea86c3b1c">mojo_errors-0.0.3-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/eb/a4/f998a6900fa01832839fd1f1bd27e989f8c13ae56c998f67a82f7242bbe0/mojo_errors-0.0.3.tar.gz#sha256=667b316c7cc1aebd2dc51cc3067165e3b51811132e209bc6b09320515d7737dc" data-requires-python="&gt;=3.8,&lt;4.0" >mojo_errors-0.0.3.tar.gz</a><br />
</body>
</html>
<!--SERIAL 20689927-->