<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo14-addon-hr-expense-exception</title>
  </head>
  <body>
    <h1>Links for odoo14-addon-hr-expense-exception</h1>
    <a href="https://files.pythonhosted.org/packages/c1/3f/00c40203a3d19af5f4e14cf904989e0248c263b8b8f34f8dcf65686ef924/odoo14_addon_hr_expense_exception-14.0.1.0.1.dev2-py3-none-any.whl#sha256=4789f91a55dc4f659ea05af97840bcf57f69e89b78efde86318dc721f29201d4" data-requires-python="&gt;=3.6" >odoo14_addon_hr_expense_exception-14.0.1.0.1.dev2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/19/c6/186ae97ca4896b460c5a0c5bf1d4586ae58eed2eb0282b7d9eacff1d6c04/odoo14_addon_hr_expense_exception-14.0.1.0.1-py3-none-any.whl#sha256=531d94653efb7e74ae539964ec3f7587a0aee6b63b403e136e5ae2a62a2ecc1f" data-requires-python="&gt;=3.6" >odoo14_addon_hr_expense_exception-14.0.1.0.1-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/a3/37/4a3abfb924ace07ef924891efa3e11b8b19058e60ebc42506f4829d0f4e9/odoo14_addon_hr_expense_exception-14.0.1.0.2.dev1-py3-none-any.whl#sha256=60b917a1d4f888de8fc4044e65b60bd63d3f1b4e8f62a4cba6b223f719056c75" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=819ecda9965232296b5e23c64f69f9ca5a2b61488590589e74ad0a90d052b091" data-core-metadata="sha256=819ecda9965232296b5e23c64f69f9ca5a2b61488590589e74ad0a90d052b091">odoo14_addon_hr_expense_exception-14.0.1.0.2.dev1-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/46/e4/9490222493f7c007352a8c2a0b4fb6e7943a7c7f4e2b3f7d1366177fd763/odoo14_addon_hr_expense_exception-14.0.1.0.2.dev3-py3-none-any.whl#sha256=80c84faaf54b90a521716f1bc48d7714acf4f8218cf3e598bafa75ae78b249a5" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=a9929a93b8d47c3a02eefbff1820bbc811e03e01a2d89a708ae83b500dff805d" data-core-metadata="sha256=a9929a93b8d47c3a02eefbff1820bbc811e03e01a2d89a708ae83b500dff805d">odoo14_addon_hr_expense_exception-14.0.1.0.2.dev3-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/7b/28/d6810d86313222c4824123c62594dcdcd1ce31b85b6b8e4c35a9624cecee/odoo14_addon_hr_expense_exception-14.0.1.0.2.dev4-py3-none-any.whl#sha256=1bdfcaa3daa5a88885db85d92766b36605452e47f43d21e947676726d15a71ed" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=abbae22e2bf9ba1a7e904456b4c223eb1943a5dce79256a6c71a838d3dbb6883" data-core-metadata="sha256=abbae22e2bf9ba1a7e904456b4c223eb1943a5dce79256a6c71a838d3dbb6883">odoo14_addon_hr_expense_exception-14.0.1.0.2.dev4-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 19579844-->