<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-hr-expense-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-hr-expense-exception</h1>
    <a href="https://files.pythonhosted.org/packages/5d/b5/a15b94439a0a089d3267bb730c5245fde4e827961778131b1c02277b3f0b/odoo_addon_hr_expense_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=37c03dfefc300e944cf8a62bdac97f5c64aa497508057ac55df31f8c79d48b4e" data-requires-python="&gt;=3.8" >odoo_addon_hr_expense_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 15616229-->