<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-stock-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-stock-exception</h1>
<a href="https://files.pythonhosted.org/packages/3b/78/4265532ccc972b92ff65da6cd3dd2beb49c7c2fd1d59f6ef9ebe8766b234/odoo_addon_stock_exception-16.0.1.0.0.1-py3-none-any.whl#sha256=f34a8b622c68ba4dc73bdb523358a22674a6ca5df7e31ecafb736cba1ad04b95" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=700fb5db14b94b13d802a1a53446a176b619be489036de6f8b10bf2548156275" data-core-metadata="sha256=700fb5db14b94b13d802a1a53446a176b619be489036de6f8b10bf2548156275">odoo_addon_stock_exception-16.0.1.0.0.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/0e/41/18c3ba7d4dd2adf66651320e3bcf916e695e2d93e2fe5331f45cc455dd38/odoo_addon_stock_exception-16.0.1.0.0.2-py3-none-any.whl#sha256=980b23d7673cd83c195b087ebe029973216922a0fa3b1378b81043cbf77f2070" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=9558a1b2daaf908119fa61c61d01fff4ffce362af766071035698781cdf64f27" data-core-metadata="sha256=9558a1b2daaf908119fa61c61d01fff4ffce362af766071035698781cdf64f27">odoo_addon_stock_exception-16.0.1.0.0.2-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 23706210-->